version: '3'

services:
  cicada:
    build: .
    volumes:
      - ./static:/static
      - ./templates:/templates
    environment:
      - CTFD_API_KEY=
      - CTFD_URL=https://krductf.ru
      - CTFD_TASK_ID=87
    networks:
      ctfnet:
        ipv4_address: 10.0.0.60

networks:
  ctfnet:
    external: true
