version: '3'

services:
  cicada:
    build: .
    volumes:
      - ./static:/static
      - ./templates:/templates
    environment:
      - CTFD_API_KEY=ctfd_2c71a65dc478092a47cdebf982b250337ba33b3f15505001fd0dbec10f62b89e
      - CTFD_URL=https://krductf.ru
      - CTFD_TASK_ID=87
    networks:
      ctfnet:
        ipv4_address: 10.0.0.60

networks:
  ctfnet:
    external: true
